linux:
  enabled: true
  image:
    repository: us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver
    tag: v0.0.12
    pullPolicy: Always
  kubeletRootDir: /var/lib/kubelet
  nodeSelector: {}
  metricsAddr: ":8080"
  nodeDriverRegistrar:
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.2.0
  livenessProbe:
    image:
      repository: quay.io/k8scsi/livenessprobe
      tag: v2.0.0
windows:
  enabled: false
  image:
    repository: us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver
    tag: v0.0.12
    pullPolicy: IfNotPresent
  kubeletRootDir: C:\var\lib\kubelet
  nodeSelector: {}
  metricsAddr: ":8080"
  nodeDriverRegistrar:
    image:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
      tag: v1.2.1-alpha.1-windows-1809-amd64
  livenessProbe:
    image:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.0.1-alpha.1-windows-1809-amd64
# .e.g: imagePullSecrets: ["nexus"] 
#         where nexus is a secret of type dockerconfig
imagePullSecrets: []

logLevel:
  debug: true

livenessProbe:
  port: 9808
  logLevel: 2

## Install Default RBAC roles and bindings
rbac:
  install: true

## Minimum Provider Versions (optional)
## A comma delimited list of key-value pairs of minimum provider versions
## e.g. provider1=0.0.2,provider2=0.0.3
minimumProviderVersions:


